#  Your global data folder is controlled by the dir.data configuration option.
#  All *.json and module.exports values from *.js files in this directory will
#  be added into a global data object available to all templates.

#  This file can be accessed using: {{ site.title }}

title: "JAM Stack e-commerce template" # Appears after the title Page eg. Title - Web Starter
description: "An e-commerce website built with 11ty.js, TailwindCSS and Foxy.io"
url: "https://foxy.io/"

author: "Foxy.io"
meta_data:
 twitter: "@"
 default_social_image: "/static/default_social_image.jpg"

foxy_cart_url: https://giof.foxycart.com/cart
currency_symbol: $

social_networks:
  blog:
    url: "https://www.foxy.io/blog/"
    icon: "fas fa-blog-square"
  email:
    url: "hello@foxy.io"
    icon: "fas fa-envelope-square"
    protocol: "mailto"
  facebook:
    url: "https://www.facebook.com/foxycart"
    icon: "fab fa-facebook-square"
  twitter:
    url: "https://twitter.com/foxycart"
    icon: "fab fa-twitter-square"
  youtube:
    url: "https://www.youtube.com/foxycart"
    icon: "fab fa-youtube"

